### ISSUE TITLE
Account loss after update

### ISSUE THREAD

**Issue by collateral87** [Rbillon59/hass-n8n#172]
After updating to version 2.0.16 i am asked to create a new account.
Does anyone alse have this issue or is there a workaround?

**Comment by jshingler** [comment]
Same issue and lost all workflows.   Luck I was able to restore from a backup and get my workflows.

**Comment by clinden** [comment]
Same issue here: asked for admin account creation and unable to use n8n because the UI is broken

**Comment by ffMathy** [comment]
Can you share your addon options etc?

**Comment by ffMathy** [comment]
> Same issue here: asked for admin account creation and unable to use n8n because the UI is broken

Can you describe how the UI is broken?

**Comment by clinden** [comment]
Addon options:
```yaml
auth: false
auth_username: ""
auth_password: ""
timezone: Europe/Paris
protocol: http
certfile: fullchain.pem
keyfile: privkey.pem
env_vars_list:
  - "WEBHOOK_URL: http://localhost:5678"
cmd_line_args: ""
```

UI doesn't load. I opened browser console as I saw DOM errors
![Image](https://github.com/user-attachments/assets/8742947b-1b59-4f33-884a-3c89df4e55a2)
