### ISSUE TITLE
Installing ffmpeg in n8n

### ISSUE THREAD

**Issue by Darisman** [Rbillon59/hass-n8n#283]
Hi
I tried to search for a way to install ffmpeg in n8n, but since it's inside home assistant there's not much explanation about it, can you please tell us how to do it

**Comment by sekertr** [comment]
I'm just thinking out loud, I couldn't try it because I don't have a camera.

First, you need to enter the following code into the `configuration.yaml `file for ffmpeg support in Home Assistant.

`ffmpeg:`

Then you should define the camera variable 

```
camera:
  - platform: ffmpeg
    name: test_camera
    input: FFMPEG_SUPPORTED_INPUT
```
After that you can use HomeAsistant node in n8n to call some actions, etc. take screenshoot. 

![Image](https://github.com/user-attachments/assets/93e71495-9a34-4852-9aef-cd97dce5c997)
